df<-read.table("household_power_consumption.txt", stringsAsFactors = FALSE, header = TRUE, sep =";")
df1<-df[df$Date=="1/2/2007" | df$Date=="2/2/2007",]
df1$Global_active_power<-as.numeric(df1[,"Global_active_power"])
df1$DT<-paste(df1$Date,df1$Time,sep=" ")
df1$DT<-strptime(df1$DT, "%d/%m/%Y %H:%M:%S")
df1$Sub_metering_1<-as.numeric(df1[,"Sub_metering_1"])
df1$Sub_metering_2<-as.numeric(df1[,"Sub_metering_2"])
df1$Sub_metering_3<-as.numeric(df1[,"Sub_metering_3"])
df1$Voltage<-as.numeric(df1[,"Voltage"])
df1$Global_reactive_power<-as.numeric(df1[,"Global_reactive_power"])
png("file4.png")
par(mfrow=c(2,2))
with(df1, plot(DT, Global_active_power, type="l", xlab="Day", ylab="Global Active Power"))
with(df1, plot(DT, Voltage, type="l", xlab="datatime", ylab="Voltage"))
with(df1, plot(DT,Sub_metering_1, type="l", ylab="Energy sub metering"))
lines(df1$DT,df1$Sub_metering_2,col="red")
lines(df1$DT,df1$Sub_metering_3,col="blue")
legend("topright",lty= 1, lwd=2,col=c("black","red","blue"),legend = c("Sub_metering_1","Sub_metering_2","Sub_metering_3"))
with(df1, plot(DT, Global_reactive_power, type="l", xlab="datatime", ylab="Global_reactive_power"))
dev.off()